version: "3"

services:

  contenter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: contenter
    cap_add:
      - SYS_ADMIN
    user: "1000:1000"
    environment:
      - "WORKERS=1"
      - "DEBUG=contenter*"
    ports:
      - "3000:3000"
    networks:
      - contenter-network

networks:
  contenter-network:
